### ISSUE TITLE
kernel_compiler_sycl_jit failed on Windows with SPV_EXT_optnone support. 

### ISSUE THREAD

**Issue by jsji** [intel/llvm#16597]
### Describe the bug

With new SPV_EXT_optnone in https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/dd33e5952bfc1ef, these following tests are failing.

The commit is temporarily reverted in pulldown [Revert "add support for SPV_EXT_optnone](https://github.com/intel/llvm/pull/16585/commits/2bae4010f11c4d0f423f2021ef10d44b6ba33560)

Please reland it first to reproduce.

https://github.com/intel/llvm/actions/runs/12702477525/job/35411634360

```
-- Testing: 2244 tests, 8 workers --
FAIL: SYCL :: KernelCompiler/kernel_compiler_sycl_jit.cpp (1674 of 2244)
******************** TEST 'SYCL :: KernelCompiler/kernel_compiler_sycl_jit.cpp' FAILED ********************
Exit Code: 9

Command Output (stdout):
--
# RUN: at line 12
D:/github/_work/llvm/llvm/install/bin/clang++.exe  -Werror  -fsycl -fsycl-targets=spir[64](https://github.com/intel/llvm/actions/runs/12702477525/job/35411634360#step:14:65)  D:\github\_work\llvm\llvm\llvm\sycl\test-e2e\KernelCompiler\kernel_compiler_sycl_jit.cpp -o D:\github\_work\llvm\llvm\build-e2e\KernelCompiler\Output\kernel_compiler_sycl_jit.cpp.tmp.out
# executed command: D:/github/_work/llvm/llvm/install/bin/clang++.exe -Werror -fsycl -fsycl-targets=spir64 'D:\github\_work\llvm\llvm\llvm\sycl\test-e2e\KernelCompiler\kernel_compiler_sycl_jit.cpp' -o 'D:\github\_work\llvm\llvm\build-e2e\KernelCompiler\Output\kernel_compiler_sycl_jit.cpp.tmp.out'
# RUN: at line 13
env ONEAPI_DEVICE_SELECTOR=level_zero:gpu  D:\github\_work\llvm\llvm\build-e2e\KernelCompiler\Output\kernel_compiler_sycl_jit.cpp.tmp.out 1
# executed command: env ONEAPI_DEVICE_SELECTOR=level_zero:gpu 'D:\github\_work\llvm\llvm\build-e2e\KernelCompiler\Output\kernel_compiler_sycl_jit.cpp.tmp.out' 1
# .---command stderr------------
# | ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 
# | ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: ze_tracing_layer.dll
# | InvalidModule: Invalid SPIR-V module: input SPIR-V module uses unknown extension 'SPV_EXT_optnone'
# `-----------------------------
# error: command failed with exit status: 9
```

**Comment by jsji** [comment]
@bashbaug @intel/dpcpp-spirv-reviewers @intel/dpcpp-esimd-reviewers FYI.

**Comment by sarnex** [comment]
@jsji These are failing in the pulldown we just merged right?

**Comment by jsji** [comment]
> [@jsji](https://github.com/jsji) These are failing in the pulldown we just merged right?

Yes, they are exposed in the latest pulldown, but the commit was reverted temporarily, so these test won't fail in sycl right now.
You need to reland the commit in llvm-spirv to reproduce.

**Comment by sarnex** [comment]
Ah ok I thought we merged with all these failures and I was gonna ask why, but this makes sense, thanks. Will investigate.

**Comment by sarnex** [comment]
Oh this isn't a real issue, basiclaly we want to skip all test tests on opencl:gpu for DG2 and we had a lit.local.cfg file to do that, but then we made a CI change so that check stopped working, but it was never caught befause we d on't test on opencl:gpu on Arc in postcommit and ESIMD tests only run if ESIMD is changed in precommit. I already fixed it [here](https://github.com/intel/llvm/commit/1677043f1e2a1bfd24f3c7b5d3349f21e7637c1a), the pulldown PR just didn't have this change.

So we can remove the ESIMD failures from this Jira, I don't know if we should re-add the llvm-spirv change. I doubt the commit is even related.

**Comment by AlexeySachkov** [comment]
> Oh this isn't a real issue, basically we want to skip all test tests on `opencl:gpu` for DG2 and we had a `lit.local.cfg` file to do that, but then we made a CI change so that check stopped working, but it was never caught because we don't test on `opencl:gpu` on Arc in postcommit and ESIMD tests only run on DG2 if ESIMD is changed in precommit and ESIMD rarely changes anymore. I already fixed it [here](https://github.com/intel/llvm/commit/1677043f1e2a1bfd24f3c7b5d3349f21e7637c1a), the pulldown PR just didn't have this change.

That explains it, thanks!

**Comment by jsji** [comment]
> Oh this isn't a real issue, basically we want to skip all these tests on `opencl:gpu` for DG2 and we had a `lit.local.cfg` file to do that, but then we made a CI change so that check stopped working, but it was never caught because we don't test on `opencl:gpu` on Arc in postcommit and ESIMD tests only run on DG2 if ESIMD is changed in precommit and ESIMD rarely changes anymore. I already fixed it [here](https://github.com/intel/llvm/commit/1677043f1e2a1bfd24f3c7b5d3349f21e7637c1a), the pulldown PR just didn't have this change.
> 
> So we can remove the ESIMD failures from this issue, I don't know if we should re-add the `llvm-spirv` change. I doubt the commit is even related.

Oh... Thanks @AlexeySachkov  and @sarnex ! Yeah, then we can remove the ESIMD failures. But we do still have the windows failures , so I will leave this open for windows .

**Comment by jopperm** [comment]
The SPIR-V translation inside the `sycl-jit` library uses a [separate set of translation options](https://github.com/intel/llvm/blob/38e6e1bf599c49d0ec4d827a90506ff8ba071c2f/sycl-jit/jit-compiler/lib/translation/SPIRVLLVMTranslation.cpp#L25); potentially these went out of sync with main DPCPP. What's the expected behaviour for `SPV_EXT_optnone`, should it be used or not by default?

CC: @sommerlukas
